### ISSUE TITLE
BigSur 11.4

### ISSUE THREAD

**Issue by chevnik-ia** [jacklukem/BigSurmountsrw#1]
Correction: But unfortunately this morning when you try to run hackintosh, it immediately loads in recovery in any case, even if you clean the frame, no matter how I found out, the utility creates a second snapshot, which is why the system does not load, it can be deleted, and the standard one is not installed, the problem is that it does not help and the system still does not start

**Comment by jacklukem** [comment]
the utility currently is only tested on Mac hardware and made only for Big Sur (or Monterey) installation with a stock snapshot booting, if you deleted snapshots and have a working "sudo mount -uw /" then you don't need the utility just use "kmutil install --update-all ; kcditto"

when you use the utility with a snapshot booting you need to replace the right kext , also shown a log where if any errors

if you need to fix "sudo mount -uw /" to delete any snapshot try this:

https://github.com/jacklukem/BigSurfixes

restore the dmg to an empty USB drive, then boot from BigSurBaseSystemfix , open Utilities and select "BigSurFixes delete snapshot", it should work also on non Mac hardware

**Comment by jacklukem** [comment]
from your machine when from bootloader do you target the BigSur System or BigSur Preboot ?

Because you should target the Preboot it's there that snapshot booting is pointed, moreover in some cases is required also to type "kcditto" to correctly copy the updated BootKernelExtensions to the target System Preboot .

Try this from CMD+S (or boot args -s):

`mount -P 1 ; mount -P 2 ; kcditto ; reboot`
